[package]
name = "ugly-graphics"
version = "0.1.5"
edition = "2024"
authors = ["PSUAN collective", "Hara Red <rtc6fg4.fejg2@gmail.com>"]
description = "Ugly graphics on CPU"
repository = "https://github.com/PSUAN/ugly-graphics"
license = "MIT"
homepage = "https://github.com/PSUAN/ugly-graphics"
documentation = "https://docs.rs/ugly-graphics"
keywords = ["graphics"]
readme = "README.md"

[features]
default = []
bitvec-adapter = ["dep:bitvec"]
image-adapter = ["dep:image"]

[dependencies]
bitvec = { version = "1.0.1", optional = true, default-features = false }
image = { version = "0.25.10", optional = true, default-features = false }

[dev-dependencies]
bitvec = { version = "1.0.1", default-features = false }
image = { version = "0.25.10", features = ["png"], default-features = false }

[[example]]
name = "adapted-bitvec"
required-features = ["bitvec-adapter"]

[[example]]
name = "outline-triangle"
required-features = ["image-adapter"]

[[example]]
name = "overlapping-triangle"
required-features = ["image-adapter"]

[[example]]
name = "tiling-triangle"
required-features = ["image-adapter"]

[[example]]
name = "minimal"
required-features = ["image-adapter"]

[[example]]
name = "lines"
required-features = ["image-adapter"]

[[example]]
name = "usage"
required-features = ["image-adapter"]
