[package]
name = "ugly"
version = "0.1.0"
edition = "2024"
authors = ["PSUAN collective", "Hara Red <rtc6fg4.fejg2@gmail.com>"]
description = "Ugly graphics on CPU"
license = "MIT"
keywords = ["graphics"]
readme = "README.md"

[features]
default = []
image-adapter = ["dep:image"]

[dependencies]
image = { version = "0.25.10", optional = true, default-features = false }

[dev-dependencies]
image = { version = "0.25.10", features = ["png"], default-features = false }

[[example]]
name = "overlapping-triangle"
required-features = [ "image-adapter" ]

[[example]]
name = "tiling-triangle"
required-features = [ "image-adapter" ]
